version: '3.1'

services:
    nginx:
        image: nginx:latest
        restart: always
        container_name: nginx_lemp
        ports:
             - "80:80"
            
        volumes:
             - ./Nginx/core:/etc/nginx/conf.d
             - ./Nginx/www:/var/www/
             - ./Nginx/Logs:/var/log/nginx/
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: db_lemp
        restart: always
   
        environment:
            MYSQL_ROOT_PASSWORD: 2021
            MYSQL_DATABASE: testdb

        volumes:
             - ./MySQL:/var/lib/mysql

    php:

        build: ./php
        container_name: php-fpm_lemp
        restart: always
        volumes:
             - ./Nginx/www:/var/www
        links:
             - db

    adminer:
        image: adminer
        container_name: adminer_lemp
        restart: always
        ports:
             - 8080:8080
